import {$,state,api,node,banner,safely} from './api.js';
import {showLog} from './render.js';
let folder='',previewPath='',fileText='',fileVersion=0,listVersion=0;
export async function preview(target){const match=target.match(/^(.*?)(?:#L?(\d+)|:(\d+))?$/);const path=decodeURIComponent(match[1]),line=Number(match[2]||match[3]||1);const version=++fileVersion;const data=await api('file?path='+encodeURIComponent(path));if(version!==fileVersion)return;previewPath=path;fileText=data.content;$('preview-name').textContent=path+(data.truncated?'（截断）':'');$('file-preview').hidden=false;$('file-line').value=line;drawLines(line);document.querySelector('.workspace').classList.add('show-inspector');selectPanel('files-panel');}
function drawLines(line=1){const pre=$('preview-code');pre.replaceChildren();fileText.split('\n').forEach((text,i)=>{const row=node('span','source-line'+(i+1===line?' selected-line':''));row.id='source-line-'+(i+1);row.append(node('span','line-number',String(i+1)),document.createTextNode(text||' '));pre.append(row);});$('source-line-'+line)?.scrollIntoView({block:'nearest'});}
function display(items){const list=$('files');list.replaceChildren();for(const item of items){const b=node('button');b.append(node('span','file-icon',item.directory?'▱':'≡'),node('span','file-name',item.path));b.onclick=safely(()=>item.directory?listFiles(item.path):preview(item.path));list.append(b);}}
export async function listFiles(path=folder){const version=++listVersion;const items=await api('files?path='+encodeURIComponent(path));if(version!==listVersion)return;folder=path;$('folder-path').textContent=path||'项目根目录';display(items);}
export function selectPanel(id){for(const b of document.querySelectorAll('[data-panel]'))b.classList.toggle('active',b.dataset.panel===id);for(const p of ['files-panel','details-panel','review-panel'])$(p).hidden=p!==id;}
export async function review(){const selected=state.selected;const data=await api('review'+(selected?'?id='+selected:''));if(selected!==state.selected)return;const list=$('review-content');list.replaceChildren();list.append(node('p','muted','工作区差异可能包含你已有的修改，不能全部归因于深蓝。'));
  if(!data.available)list.append(node('p','',data.reason||'Git 不可用；显示会话已记录的修改。'));
  const baseline=data.baseline?.files||[];const preexisting=new Set(baseline.map(x=>x.path));
  if(data.baseline){const details=node('details');details.append(node('summary','',`任务开始前已有 ${baseline.length} 个修改文件`),node('pre','',baseline.length?baseline.map(x=>x.path).join('\n'):'无已有修改'));list.append(details);}
  for(const file of data.files){const row=node('div','review-file');row.append(node('strong','',file.path),node('small','',preexisting.has(file.path)?'任务前已有修改':'当前修改（不代表独占归因）'));for(const [text,staged] of file.untracked?[['未跟踪内容',false]]:[['未暂存',false],['已暂存',true]]){const b=node('button','quiet-button',text);b.onclick=safely(async()=>{const result=await api(`diff?path=${encodeURIComponent(file.path)}&staged=${staged?1:0}`);await showLog(file.path,async()=>({content:result.content+(result.truncated?'\n[截断]':''),next:null}));});row.append(b);}list.append(row);}
  const details=node('details');details.append(node('summary','',`会话记录的文件操作 (${data.operations.length})`));for(const operation of data.operations)details.append(node('pre','',JSON.stringify(operation,null,2)));list.append(details);
}
export function initFiles(){
  $('refresh-files').onclick=safely(async()=>{await listFiles();if(previewPath)await preview(previewPath);});$('parent-folder').onclick=safely(()=>listFiles(folder.split('/').slice(0,-1).join('/')));$('close-preview').onclick=()=>{$('file-preview').hidden=true;};
  $('file-line').onchange=()=>drawLines(Math.max(1,Number($('file-line').value)));$('file-find').oninput=()=>{const at=fileText.toLowerCase().indexOf($('file-find').value.toLowerCase());if(at>=0)drawLines(fileText.slice(0,at).split('\n').length);};
  let timer;$('file-search').oninput=()=>{clearTimeout(timer);const version=++listVersion;timer=setTimeout(safely(async()=>{const query=$('file-search').value;if(!query)return listFiles();const data=await api('file-search?q='+encodeURIComponent(query));if(version===listVersion){display(data.items);$('folder-path').textContent=data.truncated?'搜索结果（有上限）':'搜索结果';}}),200);};
  $('insert-reference').onclick=()=>{if(!previewPath)return;const ref='@'+JSON.stringify(previewPath);$('prompt').setRangeText(ref,$('prompt').selectionStart,$('prompt').selectionEnd,'end');$('prompt').dispatchEvent(new Event('input'));$('prompt').focus();};
  let mentionVersion=0;$('prompt').addEventListener('input',safely(async()=>{const version=++mentionVersion,text=$('prompt').value.slice(0,$('prompt').selectionStart),match=text.match(/@([^\s@"]*)$/),menu=$('mentions');menu.replaceChildren();menu.hidden=!match;if(!match)return;const data=await api('file-search?q='+encodeURIComponent(match[1]));if(version!==mentionVersion)return;for(const item of data.items.slice(0,8)){const b=node('button','',item.path);b.type='button';b.onclick=()=>{const end=$('prompt').selectionStart;$('prompt').setRangeText('@'+JSON.stringify(item.path)+' ',end-match[0].length,end,'end');menu.hidden=true;$('prompt').dispatchEvent(new Event('input'));$('prompt').focus();};menu.append(b);}}));
  document.addEventListener('open-file',safely(e=>preview(e.detail)));
  for(const b of document.querySelectorAll('[data-panel]'))b.onclick=safely(async()=>{selectPanel(b.dataset.panel);if(b.dataset.panel==='review-panel')await review();});$('refresh-review').onclick=safely(review);
}
